# ATIVIDADE 2

# SELECIONA (HABILITAR - ATIVAR) O BANCO DE DADOS: 
USE sistema_pedidos;


#DESCRIÇÃO DA TABELA tbl_prod:
DESCRIBE tbl_prod;

#INSERÇÃO DE DADOS NA TABELA tbl_prod
INSERT INTO tbl_prod (nome, descricao, preco)VALUES
('PIZZA DE CALABRESA', 'CALABRESA E CEBOLA', 30.00),

('PIZZA DE FRANGO', 'FRANGO E CATUPIRY', 35.00),

('PIZZA DE MUSSARELA', 'MUSSARELA E TOMATE', 30.00),

('PIZZA BAIANA', 'MUSSARELA, CALABRESA E OVOS', 40.00),

('PIZZA DE BAURU', 'MUSSARELA, PRESUNTO E TOMATE', 30.00),

('PIZZA DE TOSCANA', 'MUSSARELA E CALABRESA', 35.00),

('PIZZA DE QUATRO QUEIJO', 'MUSSARELA, CATUPIRY, GANGORZOLA E PREVELONE', 45.00),

('PIZZA DE BROCOLIS', 'MUSSARELA E BROCOLIS', 35.00),

('PIZZA DE ATUM', 'MUSSARELA E ATUM', 30.00),

('PIZZA DE DOIS QUEIJO', 'MUSSARELA E CATUPIRY', 35.00);


#INSERÇÃO DE DADOS NA TABELA tbl_pedido
INSERT INTO tbl_pedido (data_pedido)VALUES
(10),
(15),
(20);


# SELEÇÃO DE DADOS DA TABELA tbl_prod:
SELECT * FROM tbl_prod;


# SELEÇÃO DE DADOS NOME E DESCRIÇÃO DA TABELA tbl_prod:
SELECT nome, descricao
FROM tbl_prod;


# SELEÇÃO DE DADOS DE APENAS UM CÓDIGO DA TABELA tbl_prod:
SELECT nome, descricao
FROM tbl_prod
WHERE cod_prod = 5;  # WHERE FILTRO PARA DETERMINAR A AÇÃO DO COMANDO  -> TRAVA DE SEGURANÇA


# SELEÇÃO DE DADOS E RENOMEAR NOME E DESCRIÇÃO DA TABELA tbl_prod:
SELECT nome AS 'PRODUTO', descricao AS 'DETALHES'
FROM tbl_prod;


# ALTERAR DADOS DA TABELA tbl_prod:
UPDATE tbl_prod SET
descricao = 'MUSSARELA E GANGORZOLA'
WHERE cod_prod = 10;   # WHERE - DETERMINA A CONDIÇÃO DO REGISTRO QUE SOFRE A ATUALIZAÇÃO  -> TRAVA DE SEGURANÇA 


UPDATE tbl_prod SET
descricao = 'MUSSARELA, ATUM E CEBOLA'
WHERE cod_prod = 9;   # WHERE - DETERMINA A CONDIÇÃO DO REGISTRO QUE SOFRE A ATUALIZAÇÃO  -> TRAVA DE SEGURANÇA 


UPDATE tbl_prod SET
descricao = 'MUSSARELA, CALABRESA, OVOS E PIMENTA'
WHERE cod_prod = 4;   # WHERE - DETERMINA A CONDIÇÃO DO REGISTRO QUE SOFRE A ATUALIZAÇÃO  -> TRAVA DE SEGURANÇA 
