# CRIAÇÃO DE BANCO DE DADOS:

CREATE DATABASE sistema_pedidos;

# SELECIONA (HABILITAR - ATIVAR) O BANCO DE DADOS: 
USE sistema_pedidos;

# CRIAÇÃO DE TABELAS:
# TABELA tbl_pedido
CREATE TABLE tbl_pedido(

	cod_ped INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,    	#UNSIGNED - SEM SINAL  ;  INT - INTEIRO  ;  AUTO_INCREMENT - INDICE NÚMERICO  ; PRIMARY KEY - CHAVE PRIMARIA
    data_pedido VARCHAR(100) NOT NULL  							#VARCHAR - TIPO DE DADO - E A QUANTIDADE DE CARACTERES  ;  NOT NULL - NÃO PODE SER NULO "0"

);

# CRIAÇÃO DA TABELA tbl_iten_pedido
CREATE TABLE tbl_iten_pedido(

	cod_prod INT(10) UNSIGNED NOT NULL,							#UNSIGNED - SEM SINAL ;  NOT NULL - NÃO PODE SER NULO "0"  ; INT - INTEIRO
    cod_ped INT(10) UNSIGNED NOT NULL							#UNSIGNED - SEM SINAL ;  NOT NULL - NÃO PODE SER NULO "0"  ; INT - INTEIRO

);

# CRIAÇÃO DA TABELA tbl_produto
CREATE TABLE tbl_prod( 

	cod_prod INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,      #UNSIGNED - SEM SINAL  ;  INT - INTEIRO  ;  AUTO_INCREMENT - INDICE NÚMERICO  ; PRIMARY KEY - CHAVE PRIMARIA
	nome VARCHAR(100) NOT NULL,								   #VARCHAR - TIPO DE DADO - E A QUANTIDADE DE CARACTERES  ;  NOT NULL - NÃO PODE SER NULO "0"
    descricao TEXT NOT NULL,								   #TEXT - TEXTO   ; NOT NULL - NÃO PODE SER NULO "0"
    preco DECIMAL(10,2)

);

# CRIAÇÃO DE CHAVES ESTRANGEIRAS:
# FK_PEDIDO
ALTER TABLE tbl_iten_pedido ADD CONSTRAINT FK_PEDIDO		  #ALTER - ALTERAÇÃO DE UMA TABELA   ; ADD CONTRANT - ADIÇÃO  ; FK_MEDICO_ESPECIALIDADE - NOME DA FK
FOREIGN KEY (cod_prod)										  #FOREIGN KEY "FK" - CHAVE ESTRANGEIRA
REFERENCES tbl_prod (cod_prod);								  #REFERENCES - REFERENCIA DE OUTRA TABELA

# CRIAÇÃO FK_ITEN_PEDIDO
ALTER TABLE tbl_iten_pedido ADD CONSTRAINT FK_ITEN_PEDIDO     #ALTER - ALTERAÇÃO DE UMA TABELA   ; ADD CONTRANT - ADIÇÃO  ; FK_MEDICO_ESPECIALIDADE - NOME DA FK
FOREIGN KEY (cod_ped)										  #FOREIGN KEY "FK" - CHAVE ESTRANGEIRA
REFERENCES tbl_pedido (cod_ped);						      #REFERENCES - REFERENCIA DE OUTRA TABELA




