# COMENTÁRIO DE LINHA

/*

20-09-2021
COMENTÁRIO DE BLOCO 
BD - 2 - ETEC DE BARUERI

*/

# CRIAÇÃO DE BANCO DE DADOS:
# AGENDAMENTOS DE CIRUGIAS
# COMANDOS SLQ - TUDO MAIUSCULO
CREATE DATABASE centro_cirugico;

# SELECIONA (HABILITAR - ATIVAR) O BANCO DE DADOS: 
USE centro_cirugico;

# LISTAR TODAS AS TABELAS DA BASE DE DADOS ATIVA:
SHOW tables;

# CRIAÇÃO DA TABELAS:

# CRIAÇÃO DA TABELA tbl_especialidade:
CREATE TABLE tbl_especialidade(

	cod_especialidade INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,  #UNSIGNED - SEM SINAL  ;  INT - INTEIRO  ;  AUTO_INCREMENT - INDICE NÚMERICO  ; PRIMARY KEY - CHAVE PRIMARIA
    nome_especialidade VARCHAR(100) NOT NULL  #VARCHAR - TIPO DE DADO - E A QUANTIDADE DE CARACTERES  ;  NOT NULL - NÃO PODE SER NULO "O"

);


DESCRIBE tbl_especialidade;  #DESCRIÇÃO DA TABELA


# CRIAÇÃO DA TABELA tbl_paciente:
CREATE TABLE tbl_paciente(

	cod_paciente INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    nome_paciente VARCHAR(500) NOT NULL,
    telefone_paciente VARCHAR(10) NOT NULL,
    celular_paciente VARCHAR(11) NOT NULL,
    email_paciente VARCHAR(100) NOT NULL,
    nome_responsavel VARCHAR(500) NULL,
    telefone_responsavel VARCHAR(10) NULL

);


# CRIAÇÃO DA TABELA tbl_medico
CREATE TABLE tbl_medico(

    cod_medico INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    cod_especialidade INT UNSIGNED NOT NULL,   #CHAVE ESTRANGEIRA
    nome_medico VARCHAR(500) NOT NULL,
    email_medico VARCHAR(100) NOT NULL,
    telefone_medico VARCHAR(10) NOT NULL,
    celular_medico VARCHAR(11) NOT NULL
    
);


#CRIAÇÃO DA TABELA tbl_insumos:
CREATE TABLE tbl_insumos(

    cod_insumos INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    cod_paciente INT UNSIGNED NOT NULL,
    nome_insumo VARCHAR(100) NOT NULL,
    quantidade_insumo DECIMAL(10,2)

);

 

#CRIAÇÃO DA TABELA tbl_sala:
CREATE TABLE tbl_sala(

    cod_sala INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    nro_sala VARCHAR(10) NOT NULL,
    cod_especialidade INT UNSIGNED NOT NULL
    
);

 

#CRIAÇÃO DA TABELA tbl_agenda:
CREATE TABLE tbl_agenda(

    cod_agenda INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    cod_sala INT UNSIGNED NOT NULL,
    cod_medico INT UNSIGNED NOT NULL,
    cod_paciente INT UNSIGNED NOT NULL,
    data_cirurgia VARCHAR(10),
    status_cirurgia ENUM('AGENDADO', 'CONCLUÍDO', 'CANCELADO')   #ENUM - INFORMAR AS LISTAS DE DADOS

);

SHOW TABLES; #VER AS TABELAS

# ALTERANDO A TABELA tbl_sala PARA A CRIAÇÃO
# DA CHAVE ESTRANGEIRA
ALTER TABLE tbl_sala ADD CONSTRAINT FK_ESPECIALIDADE  #ALTER - ALTERAÇÃO DE UMA TABELA   ; ADD CONTRANT - ADIÇÃO  ; FK_ESPECIALIDADE - NOME DA FK
FOREIGN KEY (cod_especialidade)   #FOREIGN KEY "FK" - CHAVE ESTRANGEIRA
REFERENCES tbl_especialidade (cod_especialidade);  #REFERENCES - REFERENCIA DE OUTRA TABELA

 

# CRIAÇÃO DA CHAVE ESTRANGEIRA NA TABELA
#tbl_insumos.
ALTER TABLE tbl_insumos ADD CONSTRAINT FK_PACIENTE   #ALTER - ALTERAÇÃO DE UMA TABELA   ; ADD CONTRANT - ADIÇÃO  ; FK_PACIENTE - NOME DA FK
FOREIGN KEY (cod_paciente)    #FOREIGN KEY "FK" - CHAVE ESTRANGEIRA
REFERENCES tbl_paciente(cod_paciente);    #REFERENCES - REFERENCIA DE OUTRA TABELA

 

# CRIAÇÃO DA CHAVE ESTRANGEIRA NA TABELA
#tbl_medico.
ALTER TABLE tbl_medico ADD CONSTRAINT FK_MEDICO_ESPECIALIDADE  #ALTER - ALTERAÇÃO DE UMA TABELA   ; ADD CONTRANT - ADIÇÃO  ; FK_MEDICO_ESPECIALIDADE - NOME DA FK
FOREIGN KEY (cod_especialidade)    #FOREIGN KEY "FK" - CHAVE ESTRANGEIRA
REFERENCES tbl_especialidade (cod_especialidade);    #REFERENCES - REFERENCIA DE OUTRA TABELA



#FK_SALA_AGENDA
ALTER TABLE tbl_agenda ADD CONSTRAINT FK_SALA_AGENDA
FOREIGN KEY (cod_sala)
REFERENCES tbl_sala (cod_sala);

 

#FK_MEDICO_AGENDA
ALTER TABLE tbl_agenda ADD CONSTRAINT FK_MEDICO_AGENDA
FOREIGN KEY (cod_medico)
REFERENCES tbl_medico (cod_medico);

 

#FK_PACIENTE_AGENDA
ALTER TABLE tbl_agenda ADD CONSTRAINT FK_PACIENTE_AGENDA
FOREIGN KEY (cod_paciente)
REFERENCES tbl_paciente (cod_paciente);






