# FUNÇÕES DE AGREGAÇÃO:
SELECT * FROM products;
SELECT buyPrice FROM products;

# AVG -> DETERMINA A MÉDIA DE UM GRUPO DE VALORES NÚMERICOS
SELECT AVG(buyPrice) AS 'PREÇO MÉDIO' FROM products;

# COUNT -> CONTA A QUANTIDADE DE VALORES (OU INCIDENENCIA DE VALORES) DE UMA TABELA:
SELECT * FROM products;
SELECT COUNT(*)AS 'TOTAL PRODUTOS' FROM products;

# SUM -> REALIZAR A SOMA DE UM CAMPO NÚMERICO ESPECIFICO:
SELECT * FROM products;
SELECT SUM(quantityInStock) AS 'TOTAL ESTOQUE' FROM products;
SELECT SUM(quantityInStock * buyPrice) AS 'TOTAL EM DINHEIRO' FROM products;

# MAX -> DEVOLVE O MAIOR VALOR DE UMA SERIE DE VALORES NÚMERICOS
SELECT MAX(buyPrince) AS 'MAIOR VALOR' FROM products;
SELECT buyPrice FROM products ORDER BY buyPrice DESC;   # ORDER BY DESC -> DO MAIS CARO PARA O MAIS BARATO

# MIN -> DEVOLVE O MENOR VALOR DE UMA SERIE DE VALORES NÚMERICOS
SELECT MIN(buyPrince) AS 'MENOR VALOR' FROM products;
SELECT buyPrice FROM products ORDER BY buyPrice ASC;  # ORDER BY ASC -> DO MAIS BARATO PARA O MAIS CARO

